### ISSUE TITLE
Campo não mostrar o valor no retorno dos dados.

### ISSUE THREAD

**Issue by nilonbarroso** [m4rciosouza/kz-angular2-webpack-template#3]
Funciona para inserir os dados, mas no retorno do dado no model biding, em um formulário, um campo com máscara não mostra o valor . Quando o campo com a máscara tenta mostrar um valor, simplesmente não funciona. Mesmo que esse valor esteja com a máscara ou sem, o campo não mostra os dados. Para comprovação, inclua no arquivo demo.component.ts a seguinte linha:
cpfModelMask: string = '967.486.293-57' ou cpfModelMask: string = '96748629357';
Ao carregar a view a coluna 'Valor no model' mostrar o conteúdo do campo mas a coluna 'Valor' (input com a máscara) não mostra.

**Comment by m4rciosouza** [comment]
Olá Nilton,

obrigado por reportar o problema!

Fiz uma alteração na diretiva de máscara, faltava tratar o retorno do model através da implementação do método 'writeValue'.

A máscara está funcionando corretamente agora!

**Comment by nilonbarroso** [comment]
O campo agora está sendo mostrado mas ainda apresenta um comportamento que acredito não ser o previsto. Como o valor guardado no model é sem a máscara, o valor de retorno esperado deveria ser sem a máscara. Exemplo: no arquivo demo.component.ts ser for colocado a linha cpfModelMask: string = '96748629357', o valor a ser mostrado na view é 96748629357. O valor só é mostrado com a máscara se a linha for cpfModelMask: string = '967.486.293-57'. Veja também quando existe a linha currencyModelMask: number = 4.5. O valor mostrado na view é 4.5 e não 4,50. Eu sinto muito por não poder contribuir em código mas no momento não é possível. Caso tenha como fazer doação ao projeto ficarei feliz em contribuir.

**Comment by m4rciosouza** [comment]
Olá Nilon, 
realizei outra alteração nas diretivas de máscara, e agora ao editar um valor o mesmo é exibido formatado.

**Comment by nilonbarroso** [comment]
Já testei a máscara do CPF e deu certo a correção. Agora quanto a máscara de valores monetários ainda encontrei um erro. Se for colocado no arquivo demo.component.ts a linha de código 'currencyModelMask: number = 4.5', a view irá mostrar 0,45.

Obrigado por sua atenção.

**Comment by m4rciosouza** [comment]
Olá Nilon, 
fiz a correção para esse último problema reportado, vamos torcer para estar tudo correto agora :)

**Comment by nilonbarroso** [comment]
Deu certo agora.  
Mais uma vez, obrigado.
